### ISSUE TITLE
f.split is not a function

### ISSUE THREAD

**Issue by githubcdr** [mend/renovate-on-prem#259]
# Container restarting after upgrade to 3.0.1

We see this error after upgrading;

```
ERROR: Error initializing scheduler                                                                                                                                                    "err": {
         "message": "f.split is not a function",                                                                                                                                         "stack": "TypeError: f.split is not a function\n    at Minimatch.match (/usr/src/app/node_modules/renovate/node_modules/minimatch/minimatch.js:865:11)\n    at module.e
       }                                                                                                                                                                         INFO: Using cron schedule: */5 * * * *

----
ERROR: Caught an unhandledRejection - exiting to attempt recovery. Container must be restarted                                                                                         "err": {
         "message": "f.split is not a function",                                                                                                                                         "stack": "TypeError: f.split is not a function\n    at Minimatch.match (/usr/src/app/node_modules/renovate/node_modules/minimatch/minimatch.js:865:11)\n    at module.e
       }                                                                                                                                                                        Stream closed EOF for renovatebot/renovatebot-env-0 (renovatebot)
```

Is this a regression?

**Comment by githubcdr** [comment]
Reverting to 3.0.0 resolves this for now

**Comment by morremeyer** [comment]
We are running into the same issue:

```
ERROR: Error initializing scheduler                                                                                                                                "err": {                                                                                                                                                      "message": "f.split is not a function",
         "stack": "TypeError: f.split is not a function\n    at Minimatch.match (/usr/src/app/node_modules/renovate/node_modules/minimatch/minimatch.js:865:       }
```

The container continues running until the first time the scheduler should run, then:

```
ERROR: Caught an unhandledRejection - exiting to attempt recovery. Container must be restarted
       "err": {                                                                                                                                                      "message": "f.split is not a function",                                                                                                                     "stack": "TypeError: f.split is not a function\n    at Minimatch.match (/usr/src/app/node_modules/renovate/node_modules/minimatch/minimatch.js:865:
       }
```

**Comment by rarkins** [comment]
Do you have `autodiscoverFilter` configured? If so, how/what?

**Comment by morremeyer** [comment]
We do have it configured. The error occurs with both

`autodiscoverFilter: ["orgname/*"]` 

and 

`autodiscoverFilter: "orgname/*"`

**Comment by rarkins** [comment]
This should be resolved in 3.0.2. Release notes to come

**Comment by morremeyer** [comment]
3.0.2 looks good, no more errors here. Thanks for the quick fix!
